std = "roblox"
roblox-std-source = "pinned"

[lints]
unused_variable = "warn"
shadowing = "warn"
incorrect_standard_library_use = "warn"
multiple_statements = "allow"
global_usage = "warn"
undefined_variable = "warn"
unused_function = "warn"
